### ISSUE TITLE
NPM Install Fails

### ISSUE THREAD

**Issue by edgework** [paypaldev/PayPal-JavaScript-FullStack-Standard-Checkout-Sample#1]
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://artifactory.g.devqa.gcp.dev.paypalinc.com/artifactory/api/npm/npm-all/web-streams-polyfill/-/web-streams-polyfill-3.2.1.tgz failed, reason: getaddrinfo ENOTFOUND artifactory.g.devqa.gcp.dev.paypalinc.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

Don't check in the package-lock.json  file !

**Comment by devpato** [comment]
@edgework Hi! package-lock.json files should be committed. [Here](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5) you can find several explanations on the why. 

We have fixed this issue [here](https://github.com/paypaldev/PayPal-JavaScript-FullStack-Standard-Checkout-Sample/pull/3#pullrequestreview-1563472121).

Thank you so much for creating an issue :)
